# Generated by Django 2.2.2 on 2019-08-16 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Emerging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_area', models.IntegerField(default=50)),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emerging.Intialco')),
            ],
        ),
    ]
